In [1]:
from keras.preprocessing.image import ImageDataGenerator

In [2]:
train_datagen=ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

In [3]:
x_train=train_datagen.flow_from_directory(r"C:\Users\Sri_Harshitha\Desktop\motherboard prediction\dataset\trainset",target_size=(64,64),batch_size=32,class_mode="categorical")
x_test=test_datagen.flow_from_directory(r"C:\Users\Sri_Harshitha\Desktop\motherboard prediction\dataset\testset",target_size=(64,64),batch_size=32,class_mode="categorical")

Found 32 images belonging to 8 classes.
Found 32 images belonging to 8 classes.


In [4]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

In [5]:
model=Sequential()

In [6]:
model.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation="relu"))

In [7]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [8]:
model.add(Flatten())

In [9]:
model.add(Dense(units=128,activation="relu"))

In [10]:
model.add(Dense(units = 8, activation = "softmax"))

In [11]:
model.compile(optimizer = "adam", loss ="categorical_crossentropy" , metrics = ["accuracy"] )

In [12]:
x_train.class_indices

{'IOports_Undamaged': 0,
 'IOports_damaged': 1,
 'Processor_Damaged': 2,
 'Processor_Undamaged': 3,
 'atxconnector_Damaged': 4,
 'atxconnector_Undamaged': 5,
 'cmosbattery_Undamaged': 6,
 'cmosbattery_damaged': 7}

In [16]:
model.fit(x_train, steps_per_epoch = 32//32,epochs =100  ,validation_data = x_test , validation_steps = 32//32)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.9587 - accuracy: 0.8438 - val_loss: 0.7285 - val_accuracy: 0.8438
Epoch 2/100
1/1 [==============================] - 1s 1s/step - loss: 0.9239 - accuracy: 0.8438 - val_loss: 0.6581 - val_accuracy: 0.9062
Epoch 3/100
1/1 [==============================] - 1s 1s/step - loss: 0.8562 - accuracy: 0.8750 - val_loss: 0.5810 - val_accuracy: 0.9375
Epoch 4/100
1/1 [==============================] - 1s 1s/step - loss: 0.7979 - accuracy: 0.9062 - val_loss: 0.5174 - val_accuracy: 0.9688
Epoch 5/100
1/1 [==============================] - 1s 1s/step - loss: 0.7240 - accuracy: 0.9062 - val_loss: 0.4801 - val_accuracy: 1.0000
Epoch 6/100
1/1 [==============================] - 1s 1s/step - loss: 0.6876 - accuracy: 0.9375 - val_loss: 0.4553 - val_accuracy: 0.9062
Epoch 7/100
1/1 [==============================] - 1s 1s/step - loss: 0.6155 - accuracy: 0.9375 - val_loss: 0.4206 - val_accuracy: 0.9062
Epoch 8/100
1/1 [=================

In [17]:
model.save("predictions.h5")

In [142]:
from keras.models import load_model
from keras.preprocessing import image
import numpy as np

In [143]:
model = load_model("predictions.h5")

In [144]:
img = image.load_img(r"C:\Users\Sri_Harshitha\Desktop\motherboard prediction\web\static\uploads\atx_dam_2.jpg",target_size = (64,64))

In [145]:
x = image.img_to_array(img)
x = np.expand_dims(x,axis = 0)

In [146]:
x.shape

(1, 64, 64, 3)

In [147]:
pred = model.predict(x)
pred

array([[0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)

In [148]:
f=pred.astype(int)
f

array([[0, 0, 0, 0, 1, 0, 0, 0]])

In [149]:
a1=np.array(f)
print(a1)

[[0 0 0 0 1 0 0 0]]


In [150]:
from functools import reduce


single_list = reduce(lambda x,y: x+y, a1)
print(single_list)


[0 0 0 0 1 0 0 0]


In [160]:
val=np.where(single_list==1)
dou_list = reduce(lambda x,y: x+y, val)
print(dou_list)


[4]


In [174]:
stringed = ''.join(map(str,val))
stringed
v=stringed[1]
v1= int(v)
v1

4

In [175]:
index=['IOports_Undamaged', 'IOports_damaged', 'Processor_Damaged', 'Processor_Undamaged', 'atxconnector_Damaged', 
       'atxconnector_Undamaged', 'cmosbattery_Undamaged', 'cmosbattery_damaged']

In [176]:
index[v1]

'atxconnector_Damaged'